[package]
name = "rainyproxy"
version = "0.1.0"
authors = ["meganehouser <sleepy.st818@gmail.com>"]

[dependencies.mioco]
git = "https://github.com/dpc/mioco.git"

[dependencies.clap]
clap = "2"
default-features = false

[dependencies]
httparse = "1.1"
log = "0.3"
env_logger = "0.3"
